name: Build
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      branding:
        description: "Include drivers"
        required: true
        default: "all"
        type: choice
        options:
          - none
          - all
          - hp
          - dell
          - lenovo
      MDT:
        description: "Include MDT"
        default: false
        required: true
        type: boolean

jobs:
  build:
    env:
      INPUT_BRANDING: ${{ github.event.inputs.branding }}
      INPUT_MDT: ${{ github.event.inputs.MDT }}
    runs-on: windows-latest
    steps:
      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install ADK
        shell: pwsh
        run: choco install windows-adk-all -y

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build WinPE Image
        shell: pwsh
        run: .\build.ps1 -branding $env:INPUT_BRANDING -mdt $($env:INPUT_MDT -eq '1') -arch "amd64" -workingDirectory $env:GITHUB_WORKSPACE

      - name: upload artifact
        if: ${{!startsWith(github.ref,'refs/tags/')}}
        uses: actions/upload-artifact@v4
        with:
          name: WinPE
          path: |
            .\WinPE_*.iso
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref,'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            WinPE_*.iso
